apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-lab
  labels:
    app: gitops-lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops-lab
  template:
    metadata:
      labels:
        app: gitops-lab
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80