apiVersion: v1
kind: Service
metadata:
  name: postgres-local-path
  namespace: storage-lab
spec:
  clusterIP: None
  selector:
    app: postgres-local-path
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-local-path
  namespace: storage-lab
spec:
  serviceName: postgres-local-path
  replicas: 1
  selector:
    matchLabels:
      app: postgres-local-path
  template:
    metadata:
      labels:
        app: postgres-local-path
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: password123
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
