apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-app-uat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:thaunghtike-share/gitops-lab.git
    targetRevision: main
    path: helm-charts/gitops-demo-app
    helm:
      valueFiles:
        - values-uat.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: uat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true